/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_eagleview_ljr_ndkdemo_MainActivity */

#ifndef _Included_cn_eagleview_ljr_ndkdemo_MainActivity
#define _Included_cn_eagleview_ljr_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_eagleview_ljr_ndkdemo_MainActivity
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_eagleview_ljr_ndkdemo_MainActivity_getStrFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
